### PR TITLE
docs: updated the tutorial documents for @apollo/client@3.0.0

### PR DESCRIPTION
**Pull request by thomasJs8**
Hi, there.

# Summary
As you know, [Apollo Client v3.0.0](https://github.com/apollographql/apollo-client/releases/tag/v3.0.0) has been released, then things can be imported from `@apollo/client`.
Speaking of which, we have to update documents for the tutorial.
So, now I create a pull request.

# Details
I just modified parts of the import statement in the documents.
I cared about the alphabetical order and comma.

Please let me know if there is a typo or something I have to fix.

Thanks :D

### CODE REVIEW

**Comment by cameronbaney** [comment]
This was very helpful in getting through some of the tutorial now that Apollo Client v3.0.0 has been released. I ran into some issues in 8. Update data with mutations, specifically around `cache.writeData()` as that [has been fully removed](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#cache-improvements).

I'm totally new at Apollo, so I am still trying to figure out the difference between the old and new way to do it, so I cannot help update these docs anymore than pointing it out. When I figure it out, I can help update that area.

**Comment by thomasJs8** [comment]
@cameronbaney 
Hi, there!
Thanks for your help, I appreciate it. 
I just removed code that includes `cache.writeData({})`.

Memo:
I think the `link` instance inside `ApolloClient` should be changed like [this](https://github.com/apollographql/fullstack-tutorial/blob/master/final/client/src/index.tsx#L27), but it still works.
So I didn't do anything about it.

**Comment by thomasJs8** [comment]
@StephenBarlow 
I'm sorry for mentioning.
I just wanna know the Apollo GraphQL team has already been working on the tutorial documents for Apollo Client v3.0.0.
If so, I need to close this PR.

Thanks :D

**Comment by thomasJs8** [comment]
@hwillson 
Hi!
I saw [your PR](https://github.com/apollographql/apollo/pull/956), then I guess you are still working on updating documents for @apollo/client v3.0.0.

I need to close this PR if you are working on this.
Should I do this?

Thanks :D

**Comment by ychi** [comment]
I ran into some issue reading Chap. 8 Mutations and Chap. 9 Local states, too(the `cache.writeData()`). Source codes in `final/` are aligned with 3.x API, though. 

Is there a plan to update soon? If not, I am willing to help :)

**Comment by thomasJs8** [comment]
@ychi 
Hi, there :D

The Apollo core team is working on this update(v3.x.x) right away on other issues.
This PR covers a lot of things in the docs and is outdated now.
So you have better create an issue or a PR if you find something.

Thanks for your comment!

**Comment by thomasJs8** [comment]
This PR makes people confused right now.
I close this.

Please create an issue or a PR if you find something.

Thanks :D

**Pull request closed without merging**
