### PR TITLE
📃 Add links to edit the docs

### PR DESCRIPTION
**Pull request by stefanoeb**
Well, this is very meta but I like to have links to make a PR/issue specially because there is no edit button on mobile devices.

### CODE REVIEW

**Comment by trevorblades** [comment]
Thanks @stefanoeb! This makes me feel like maybe we should just move the "Edit on GitHub" link from the right sidebar when the layout adjusts for mobile. I'll bring this up within the team and try to make this happen 👍

**Comment by trevorblades** [comment]
You can see our proposed change (still WIP) here: https://deploy-preview-614--apollo-docs-index.netlify.com/docs/tutorial/schema/

Just make your screen small enough to hide the right sidebar and scroll to the bottom!

9d3c499cf959daaca7c3a648cf829621

**Comment by StephenBarlow** [comment]
@trevorblades 's update to include the "Edit on GitHub" link on mobile layout is live! Closing this PR in favor of that functionality, but thanks for the PR @stefanoeb!

**Comment by stefanoeb** [comment]
💯

**Pull request closed without merging**
