### PR TITLE
Update preflight script docs with API

### PR DESCRIPTION
**Pull request by Jephuff**
Add documentation for the different helpers in preflight scripts
image

### CODE REVIEW

**Comment by papollosc** [comment]
Tis dope. I would rely on @StephenBarlow for language clarity. Wondering if we want to add the snippet titles (`Send request`, `get variable`, `set variable`, `Request user input`)  so it is easy to recognize? But that would make it four columns, not sure if that is encouraged. 
image

**Review by papollosc — COMMENTED** [review]
Tis dope. I would rely on @StephenBarlow for language clarity. Wondering if we want to add the snippet titles (`Send request`, `Get variable`, `Set variable`, `Request user input`)  so it is easy to recognize? But that would make it four columns, not sure if that is encouraged. 
image

**Comment by StephenBarlow** [comment]
Oh hey nice! We have a special table format that we use for API references such as these for extra snazziness. Tomorrow I'll put together a PR against _this_ PR to convert it, plus any language tweaks.

**Review by papollosc — APPROVED** [review]
🥳 🙇‍♀️

**Pull request merged**
